mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include

#from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('pybo/', views.index), ##pybo/ URL이 요청되면 views.index를 호출하라
    path('pybo/', include('pybo.urls')),
    #위에서 아래로 이동 config로 갈 필요 없이 pybo app 하위 파일에서 진행
]

mysite/pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name = 'index'),
    # """pybo/ URL은 다음처럼 config/urls.py 파일에 매핑된 pybo/ 와
    # pybo/urls.py 파일에 매핑된 '' 이 더해져 pybo/가 된다."""
    path('<int:question_id>/', views.detail, name ='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

mysite/pybo/models.py
from django.db import models

# Create your models here.
from django.db import models

# 질문 모델에 필요한 속성들. 질문 제목, 내용, 작성한 일시
class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject # id 값 대신 제목 표시

# 질문, 답변의 내용, 답변 작성 일시
class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)# 답변과 연결된 질문이 삭제될 경우 답변도 함께 삭제된다.
    content = models.TextField()
    create_date = models.DateTimeField()
# 기존 모델을 속성으로 연결하려면 Foreignkey를 사용해야 한다. Foreignkey는 다른 모델과 연결하기 위해
#사용한다.

mysite/pybo/forms.py
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm): # forms.ModelForm 상속
    class Meta:
        model = Question # 사용할 모델
        fields = ['subject', 'content'] # QuestionForm에서 사용할 QUestion 모델의 속성
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }
        labels = {
            'subject': '제목',
            'content': '내용',
        }



class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }
    # 장고의 폼 일반 폼과 모델 폼으로 나뉜다.
# 모델 폼: 모델과 연결된 폼으로 폼을 저장하면 연결된 모델의 데이터를 저장할수 있는 폼이다. 이너 클래스인 Meta 클래스가 반드시 필요.
# Meta 클래스에는 사용할 모델과 모델의 속성을 적어야 한다.

mysite/pybo/views.py
from django.http import HttpResponseNotAllowed
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Question
from .forms import QuestionForm, AnswerForm

def index(request):
    question_list = Question.objects.order_by('-create_date') # 질문목록 획득, order by는 조회 결과를 (역순으로 > -)정렬하는 함수.
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)
    #render : 파이썬 데이터를 템플릿에 적용하여 HTML로 반환. .html 파일을 템플릿 파일이라고 함

def detail(request, question_id): # pybo 내용 출력
    question = get_object_or_404(Question, pk=question_id) # pk는 Question 모델의 기본키(Primary Key)에 해당하는 값을 의미한다.
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

## 답변등록
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

def question_create(request):
    form = QuestionForm()
    return render(request, 'pybo/question_form.html', {'form': form}) # 템플릿에서 질문 등록시 사용할 폼 엘리먼트를 생성

## 질문등록
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid(): # 폼이 유효한 경우
            question = form.save(commit=False) # 임시 저장(커밋=폴스)하여 QUESTION 객체를 리턴받는다.
            question.create_date = timezone.now() # 실제 저장을 위해 작성일시 설정
            question.save() # 데이터를 실제로 저장
            return redirect('pybo:index')
    else: #GET 방식일 경우 URL을 전달받아 질문 등록 화면 렌더링
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start, base.html을 상속한 템플릿에서 개별적으로 구현 -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

mysite/templates/pybo/question_detail.html
{#질문상세 #}
{#{% load static %}#}
{#<link rel="stylesheet" type = "text/css" href="{% static 'bootstrap.min.css' %}">#}
{#<h1>{{ question.subject }}</h1>#}
{#<div>#}
{#    {{ question.content }}#}
{#</div>#}
{#<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>#}
{#<div>#}
{#    <ul>#}
{#    {% for answer in question.answer_set.all %}#}
{#        <li>{{ answer.content }}</li>#}
{#    {% endfor %}#}
{#    </ul>#}
{#</div>#}
{#<form action="{% url 'pybo:answer_create' question.id %}" method="post">#}
{#{% csrf_token %}#}
{#    보안에 관련된 항목으로 form으로 전송한 데이터가 실제 웹 페이지에서#}
{#    작성한 데이터인지를 판단하는 가늠자 역할을 한다.#}
{#     post 요청시 form 태그에 필수적임#}
{#<textarea name="content" id="content" rows="15"></textarea>#}
{#<input type="submit" value="답변등록">#}
{#</form>#}
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="'border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

mysite/templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}
    <div class = "container">
    <h5 class = "my-3 border-buttom pb-2">질문등록</h5>
    <form method ="post"> <!--form 태그에 action 속성을 지정하지 않으면 현재 페이지의 URL이 디폴트 action으로 설정된다.-->
        <!-- 여기서 action 속성을 지정하지 않은 이유는 직접적으로 지정하면 question_form.html 템플릿은 질문등록에서만 사용 가능하기 때문.
        이후 질문 수정에서 재활용이 불가능하다. 왜냐면 질문 수정일 경우 action 값을 다르게 해야하기 때문이다.-->
        {% csrf_token %}
{#        {{ form.as_p }}#}
{#        form은 question_create 함수에서 전달한 QuestionForm의 객체이다.#}
{#        폼에 정의한 subject, content 속성에 해당하는 HTML 코드를 자동으로 생성한다.#}
     <!-- 내용에 해당되는 내용 직접 작성 -->
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">  <!--오류가 발생한 경우 기존에 입력했던 값을 유지하기 위해 작성 -->
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type = "submit" class="btn btn-primary">저장하기</button>
    </form>
    </div>
{% endblock %}

mysite/templates/pybo/question_list.html
{#{% load static %}#}
{#<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">#}
{% extends 'base.html' %} <!--base.html상속 -->
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
<a href="{% url 'pybo:question_create' %}" class="btn-primary">질문 등록</a> <!--btn btn-primary 클래스를 적용하면 버튼으로 보인다. -->
</div>
{% endblock %}